<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWP8FjR0\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWP8FjR0/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerWP8FjR0.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerWP8FjR0\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerWP8FjR0\App_KernelProdContainer([
    'container.build_hash' => 'WP8FjR0',
    'container.build_id' => '9fd09657',
    'container.build_time' => 1766146746,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWP8FjR0');
