<?php

namespace ContainerWP8FjR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttachmentsFieldSoftDeleteHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Service\Fields\Attachments\DeleteHandlers\AttachmentsFieldSoftDeleteHandler' shared autowired service.
     *
     * @return \App\Module\Service\Fields\Attachments\DeleteHandlers\AttachmentsFieldSoftDeleteHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['App\\Module\\Service\\Fields\\Attachments\\DeleteHandlers\\AttachmentsFieldSoftDeleteHandler'] = $container->createProxy('AttachmentsFieldSoftDeleteHandlerGhostA3f6f98', static fn () => \AttachmentsFieldSoftDeleteHandlerGhostA3f6f98::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Data'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Record'.\DIRECTORY_SEPARATOR.'RecordDeleteHandlers'.\DIRECTORY_SEPARATOR.'BaseModuleDeleteHandlerInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Data'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Record'.\DIRECTORY_SEPARATOR.'RecordDeleteHandlers'.\DIRECTORY_SEPARATOR.'RecordFieldTypeDeleteHandlerInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Module'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fields'.\DIRECTORY_SEPARATOR.'Attachments'.\DIRECTORY_SEPARATOR.'DeleteHandlers'.\DIRECTORY_SEPARATOR.'AttachmentsFieldSoftDeleteHandler.php';

        return ($lazyLoad->__construct(($container->privates['App\\MediaObjects\\Repository\\DefaultMediaObjectManager'] ?? self::getDefaultMediaObjectManagerService($container)), ($container->privates['App\\Module\\LegacyHandler\\ModuleNameMapperHandler'] ?? self::getModuleNameMapperHandlerService($container))) && false ?: $lazyLoad);
    }
}
