<?php

namespace ContainerWP8FjR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandLastRunTrackerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Install\Service\CommandLastRunTracker' shared autowired service.
     *
     * @return \App\Install\Service\CommandLastRunTracker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Install'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CommandLastRunTracker.php';

        $a = ($container->privates['App\\Data\\LegacyHandler\\PreparedStatementHandler'] ?? $container->load('getPreparedStatementHandlerService'));

        if (isset($container->privates['App\\Install\\Service\\CommandLastRunTracker'])) {
            return $container->privates['App\\Install\\Service\\CommandLastRunTracker'];
        }

        return $container->privates['App\\Install\\Service\\CommandLastRunTracker'] = new \App\Install\Service\CommandLastRunTracker($a, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ($container->privates['App\\DateTime\\LegacyHandler\\DateTimeHandler'] ?? $container->load('getDateTimeHandlerService')));
    }
}
