<?php

namespace ContainerWP8FjR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailMarketingTrackersEnabledMapperService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\EmailMarketing\FieldDefinitions\EmailMarketingTrackersEnabledMapper' shared autowired service.
     *
     * @return \App\Module\EmailMarketing\FieldDefinitions\EmailMarketingTrackersEnabledMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'FieldDefinitions'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'VardefConfigMapperInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'modules'.\DIRECTORY_SEPARATOR.'EmailMarketing'.\DIRECTORY_SEPARATOR.'FieldDefinitions'.\DIRECTORY_SEPARATOR.'EmailMarketingTrackersEnabledMapper.php';

        $a = ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Trackers\\DefaultEmailTrackerManager'] ?? $container->load('getDefaultEmailTrackerManagerService'));

        if (isset($container->privates['App\\Module\\EmailMarketing\\FieldDefinitions\\EmailMarketingTrackersEnabledMapper'])) {
            return $container->privates['App\\Module\\EmailMarketing\\FieldDefinitions\\EmailMarketingTrackersEnabledMapper'];
        }

        return $container->privates['App\\Module\\EmailMarketing\\FieldDefinitions\\EmailMarketingTrackersEnabledMapper'] = new \App\Module\EmailMarketing\FieldDefinitions\EmailMarketingTrackersEnabledMapper($a);
    }
}
