<?php

namespace ContainerWP8FjR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntryPointControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\EntryPoint\Controller\EntryPointController' shared autowired service.
     *
     * @return \App\EntryPoint\Controller\EntryPointController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'EntryPoint'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'EntryPointController.php';

        $container->services['App\\EntryPoint\\Controller\\EntryPointController'] = $instance = new \App\EntryPoint\Controller\EntryPointController();

        $instance->setContainer(($container->privates['.service_locator.VUN9NvY'] ?? $container->load('get_ServiceLocator_VUN9NvYService'))->withContext('App\\EntryPoint\\Controller\\EntryPointController', $container));

        return $instance;
    }
}
