<?php

namespace ContainerWP8FjR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHasPrimaryEmailAddressService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Campaigns\Service\Email\Targets\Validation\Validators\Default\HasPrimaryEmailAddress' shared autowired service.
     *
     * @return \App\Module\Campaigns\Service\Email\Targets\Validation\Validators\Default\HasPrimaryEmailAddress
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'modules'.\DIRECTORY_SEPARATOR.'Campaigns'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Email'.\DIRECTORY_SEPARATOR.'Targets'.\DIRECTORY_SEPARATOR.'Validation'.\DIRECTORY_SEPARATOR.'EmailTargetValidatorInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'modules'.\DIRECTORY_SEPARATOR.'Campaigns'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Email'.\DIRECTORY_SEPARATOR.'Targets'.\DIRECTORY_SEPARATOR.'Validation'.\DIRECTORY_SEPARATOR.'BaseEmailTargetValidator.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'modules'.\DIRECTORY_SEPARATOR.'Campaigns'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Email'.\DIRECTORY_SEPARATOR.'Targets'.\DIRECTORY_SEPARATOR.'Validation'.\DIRECTORY_SEPARATOR.'Validators'.\DIRECTORY_SEPARATOR.'Default'.\DIRECTORY_SEPARATOR.'HasPrimaryEmailAddress.php';

        return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\Validation\\Validators\\Default\\HasPrimaryEmailAddress'] = new \App\Module\Campaigns\Service\Email\Targets\Validation\Validators\Default\HasPrimaryEmailAddress(($container->privates['App\\Emails\\Service\\Validation\\EmailValidationHelper'] ?? $container->load('getEmailValidationHelperService')));
    }
}
