<?php

namespace ContainerWP8FjR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInitCurrencyDefaultService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\EmailMarketing\Service\Fields\InitCurrencyDefault' shared autowired service.
     *
     * @return \App\Module\EmailMarketing\Service\Fields\InitCurrencyDefault
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Process'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ProcessHandlerInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'modules'.\DIRECTORY_SEPARATOR.'EmailMarketing'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fields'.\DIRECTORY_SEPARATOR.'InitCurrencyDefault.php';

        $a = ($container->privates['App\\UserPreferences\\LegacyHandler\\UserPreferenceHandler'] ?? $container->load('getUserPreferenceHandlerService'));

        if (isset($container->privates['App\\Module\\EmailMarketing\\Service\\Fields\\InitCurrencyDefault'])) {
            return $container->privates['App\\Module\\EmailMarketing\\Service\\Fields\\InitCurrencyDefault'];
        }

        return $container->privates['App\\Module\\EmailMarketing\\Service\\Fields\\InitCurrencyDefault'] = new \App\Module\EmailMarketing\Service\Fields\InitCurrencyDefault($a);
    }
}
