<?php

namespace ContainerWP8FjR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPublic_Documents_StorageService extends App_KernelProdContainer
{
    /*
     * Gets the private 'public.documents.storage' shared service.
     *
     * @return \League\Flysystem\Filesystem
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'league'.\DIRECTORY_SEPARATOR.'flysystem'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'FilesystemReader.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'league'.\DIRECTORY_SEPARATOR.'flysystem'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'FilesystemWriter.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'league'.\DIRECTORY_SEPARATOR.'flysystem'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'FilesystemOperator.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'league'.\DIRECTORY_SEPARATOR.'flysystem'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'CalculateChecksumFromStream.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'league'.\DIRECTORY_SEPARATOR.'flysystem'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Filesystem.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'league'.\DIRECTORY_SEPARATOR.'flysystem'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'FilesystemAdapter.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'league'.\DIRECTORY_SEPARATOR.'flysystem'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ChecksumProvider.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'league'.\DIRECTORY_SEPARATOR.'flysystem-local'.\DIRECTORY_SEPARATOR.'LocalFilesystemAdapter.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'league'.\DIRECTORY_SEPARATOR.'flysystem'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'UnixVisibility'.\DIRECTORY_SEPARATOR.'VisibilityConverter.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'league'.\DIRECTORY_SEPARATOR.'flysystem'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'UnixVisibility'.\DIRECTORY_SEPARATOR.'PortableVisibilityConverter.php';

        return $container->privates['public.documents.storage'] = new \League\Flysystem\Filesystem(new \League\Flysystem\Local\LocalFilesystemAdapter((\dirname(__DIR__, 3).'/public/media-upload/documents'), \League\Flysystem\UnixVisibility\PortableVisibilityConverter::fromArray(['file' => ['public' => 420, 'private' => 384], 'dir' => ['public' => 493, 'private' => 448]], 'private'), 0, 2, NULL, false), ['visibility' => NULL, 'directory_visibility' => NULL, 'case_sensitive' => true, 'disable_asserts' => false, 'public_url' => NULL], NULL, NULL, NULL);
    }
}
