<?php

namespace ContainerWP8FjR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecordDeleteHandlerRegistryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Data\Service\Record\RecordDeleteHandlers\RecordDeleteHandlerRegistry' shared autowired service.
     *
     * @return \App\Data\Service\Record\RecordDeleteHandlers\RecordDeleteHandlerRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['App\\Data\\Service\\Record\\RecordDeleteHandlers\\RecordDeleteHandlerRegistry'] = $container->createProxy('RecordDeleteHandlerRegistryGhostF615e8a', static fn () => \RecordDeleteHandlerRegistryGhostF615e8a::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Data'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Record'.\DIRECTORY_SEPARATOR.'RecordDeleteHandlers'.\DIRECTORY_SEPARATOR.'RecordDeleteHandlerRegistryInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Data'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Record'.\DIRECTORY_SEPARATOR.'RecordDeleteHandlers'.\DIRECTORY_SEPARATOR.'ModuleDeleteHandlerTrait.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Data'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Record'.\DIRECTORY_SEPARATOR.'RecordDeleteHandlers'.\DIRECTORY_SEPARATOR.'RecordDeleteHandlerTrait.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Data'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Record'.\DIRECTORY_SEPARATOR.'RecordDeleteHandlers'.\DIRECTORY_SEPARATOR.'RecordDeleteHandlerRegistry.php';

        return ($lazyLoad->__construct(new RewindableGenerator(fn () => new \EmptyIterator(), 0)) && false ?: $lazyLoad);
    }
}
