<?php

namespace ContainerWP8FjR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSurveyURLParserService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Campaigns\Service\Email\Parser\Parsers\SurveyURLParser' shared autowired service.
     *
     * @return \App\Module\Campaigns\Service\Email\Parser\Parsers\SurveyURLParser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'modules'.\DIRECTORY_SEPARATOR.'Campaigns'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Email'.\DIRECTORY_SEPARATOR.'Parser'.\DIRECTORY_SEPARATOR.'CampaignEmailParserInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'modules'.\DIRECTORY_SEPARATOR.'Campaigns'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Email'.\DIRECTORY_SEPARATOR.'Parser'.\DIRECTORY_SEPARATOR.'Parsers'.\DIRECTORY_SEPARATOR.'SurveyURLParser.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Data'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'RecordTemplate'.\DIRECTORY_SEPARATOR.'RecordTemplateManagerInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Data'.\DIRECTORY_SEPARATOR.'LegacyHandler'.\DIRECTORY_SEPARATOR.'RecordTemplate'.\DIRECTORY_SEPARATOR.'RecordTemplateHandler.php';

        $a = ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Trackers\\DefaultEmailTrackerManager'] ?? $container->load('getDefaultEmailTrackerManagerService'));

        if (isset($container->privates['App\\Module\\Campaigns\\Service\\Email\\Parser\\Parsers\\SurveyURLParser'])) {
            return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Parser\\Parsers\\SurveyURLParser'];
        }

        return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Parser\\Parsers\\SurveyURLParser'] = new \App\Module\Campaigns\Service\Email\Parser\Parsers\SurveyURLParser($a, new \App\Data\LegacyHandler\RecordTemplate\RecordTemplateHandler(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState()), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['App\\Module\\LegacyHandler\\ModuleNameMapperHandler'] ?? self::getModuleNameMapperHandlerService($container))), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
