<?php

namespace ContainerWP8FjR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSupportedImageTypeUploadValidatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\MediaObjects\Validator\UploadValidator\Validators\SupportedImageTypeUploadValidator' shared autowired service.
     *
     * @return \App\MediaObjects\Validator\UploadValidator\Validators\SupportedImageTypeUploadValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'MediaObjects'.\DIRECTORY_SEPARATOR.'Validator'.\DIRECTORY_SEPARATOR.'UploadValidator'.\DIRECTORY_SEPARATOR.'UploadValidatorInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'MediaObjects'.\DIRECTORY_SEPARATOR.'Validator'.\DIRECTORY_SEPARATOR.'UploadValidator'.\DIRECTORY_SEPARATOR.'Validators'.\DIRECTORY_SEPARATOR.'SupportedImageTypeUploadValidator.php';

        return $container->privates['App\\MediaObjects\\Validator\\UploadValidator\\Validators\\SupportedImageTypeUploadValidator'] = new \App\MediaObjects\Validator\UploadValidator\Validators\SupportedImageTypeUploadValidator(($container->services['app.system-configs'] ?? $container->load('getApp_SystemconfigsService')));
    }
}
