<?php

namespace ContainerWP8FjR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrackerHeaderParserService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Campaigns\Service\Email\Parser\Parsers\TrackerHeaderParser' shared autowired service.
     *
     * @return \App\Module\Campaigns\Service\Email\Parser\Parsers\TrackerHeaderParser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'modules'.\DIRECTORY_SEPARATOR.'Campaigns'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Email'.\DIRECTORY_SEPARATOR.'Parser'.\DIRECTORY_SEPARATOR.'CampaignEmailParserInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'modules'.\DIRECTORY_SEPARATOR.'Campaigns'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Email'.\DIRECTORY_SEPARATOR.'Parser'.\DIRECTORY_SEPARATOR.'Parsers'.\DIRECTORY_SEPARATOR.'TrackerHeaderParser.php';

        $a = ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Trackers\\DefaultEmailTrackerManager'] ?? $container->load('getDefaultEmailTrackerManagerService'));

        if (isset($container->privates['App\\Module\\Campaigns\\Service\\Email\\Parser\\Parsers\\TrackerHeaderParser'])) {
            return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Parser\\Parsers\\TrackerHeaderParser'];
        }

        return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Parser\\Parsers\\TrackerHeaderParser'] = new \App\Module\Campaigns\Service\Email\Parser\Parsers\TrackerHeaderParser($a, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
