<?php

namespace ContainerWP8FjR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrackersEnabledRetrieveApiMapperService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\EmailMarketing\Service\Fields\TrackersEnabledRetrieveApiMapper' shared autowired service.
     *
     * @return \App\Module\EmailMarketing\Service\Fields\TrackersEnabledRetrieveApiMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Data'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Record'.\DIRECTORY_SEPARATOR.'Mappers'.\DIRECTORY_SEPARATOR.'BaseModuleMapperInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Data'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Record'.\DIRECTORY_SEPARATOR.'Mappers'.\DIRECTORY_SEPARATOR.'BaseFieldMapperInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Data'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Record'.\DIRECTORY_SEPARATOR.'ApiRecordMappers'.\DIRECTORY_SEPARATOR.'ApiRecordFieldMapperInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'modules'.\DIRECTORY_SEPARATOR.'EmailMarketing'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Fields'.\DIRECTORY_SEPARATOR.'TrackersEnabledRetrieveApiMapper.php';

        $a = ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Trackers\\DefaultEmailTrackerManager'] ?? $container->load('getDefaultEmailTrackerManagerService'));

        if (isset($container->privates['App\\Module\\EmailMarketing\\Service\\Fields\\TrackersEnabledRetrieveApiMapper'])) {
            return $container->privates['App\\Module\\EmailMarketing\\Service\\Fields\\TrackersEnabledRetrieveApiMapper'];
        }

        return $container->privates['App\\Module\\EmailMarketing\\Service\\Fields\\TrackersEnabledRetrieveApiMapper'] = new \App\Module\EmailMarketing\Service\Fields\TrackersEnabledRetrieveApiMapper($a);
    }
}
