<?php

namespace ContainerWP8FjR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUnsubscribeValidatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\EmailMarketing\LegacyHandler\Validation\Validators\UnsubscribeValidator' shared autowired service.
     *
     * @return \App\Module\EmailMarketing\LegacyHandler\Validation\Validators\UnsubscribeValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Process'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ProcessHandlerInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'modules'.\DIRECTORY_SEPARATOR.'EmailMarketing'.\DIRECTORY_SEPARATOR.'LegacyHandler'.\DIRECTORY_SEPARATOR.'Validation'.\DIRECTORY_SEPARATOR.'Validators'.\DIRECTORY_SEPARATOR.'UnsubscribeValidator.php';

        $a = ($container->privates['App\\Data\\LegacyHandler\\PreparedStatementHandler'] ?? $container->load('getPreparedStatementHandlerService'));

        if (isset($container->privates['App\\Module\\EmailMarketing\\LegacyHandler\\Validation\\Validators\\UnsubscribeValidator'])) {
            return $container->privates['App\\Module\\EmailMarketing\\LegacyHandler\\Validation\\Validators\\UnsubscribeValidator'];
        }

        return $container->privates['App\\Module\\EmailMarketing\\LegacyHandler\\Validation\\Validators\\UnsubscribeValidator'] = new \App\Module\EmailMarketing\LegacyHandler\Validation\Validators\UnsubscribeValidator($a, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
