<?php

namespace ContainerWP8FjR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaignsCreateUnsubscribeListService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Campaigns\Service\Record\SaveHandlers\CampaignsCreateUnsubscribeList' shared autowired service.
     *
     * @return \App\Module\Campaigns\Service\Record\SaveHandlers\CampaignsCreateUnsubscribeList
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Data'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Record'.\DIRECTORY_SEPARATOR.'RecordSaveHandlers'.\DIRECTORY_SEPARATOR.'BaseModuleSaveHandlerInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Data'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Record'.\DIRECTORY_SEPARATOR.'RecordSaveHandlers'.\DIRECTORY_SEPARATOR.'RecordSaveHandlerInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'modules'.\DIRECTORY_SEPARATOR.'Campaigns'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Record'.\DIRECTORY_SEPARATOR.'SaveHandlers'.\DIRECTORY_SEPARATOR.'CampaignsCreateUnsubscribeList.php';

        $a = ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\DefaultEmailSuppressionListManager'] ?? $container->load('getDefaultEmailSuppressionListManagerService'));

        if (isset($container->privates['App\\Module\\Campaigns\\Service\\Record\\SaveHandlers\\CampaignsCreateUnsubscribeList'])) {
            return $container->privates['App\\Module\\Campaigns\\Service\\Record\\SaveHandlers\\CampaignsCreateUnsubscribeList'];
        }

        return $container->privates['App\\Module\\Campaigns\\Service\\Record\\SaveHandlers\\CampaignsCreateUnsubscribeList'] = new \App\Module\Campaigns\Service\Record\SaveHandlers\CampaignsCreateUnsubscribeList($a);
    }
}
