<?php

namespace ContainerWP8FjR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteTestMailMarketingEntriesServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\EmailMarketing\Service\Actions\DeleteTestMailMarketingEntriesService' shared autowired service.
     *
     * @return \App\Module\EmailMarketing\Service\Actions\DeleteTestMailMarketingEntriesService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'modules'.\DIRECTORY_SEPARATOR.'EmailMarketing'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'DeleteTestMailMarketingEntriesService.php';

        $a = ($container->privates['App\\Data\\LegacyHandler\\PreparedStatementHandler'] ?? $container->load('getPreparedStatementHandlerService'));

        if (isset($container->privates['App\\Module\\EmailMarketing\\Service\\Actions\\DeleteTestMailMarketingEntriesService'])) {
            return $container->privates['App\\Module\\EmailMarketing\\Service\\Actions\\DeleteTestMailMarketingEntriesService'];
        }

        return $container->privates['App\\Module\\EmailMarketing\\Service\\Actions\\DeleteTestMailMarketingEntriesService'] = new \App\Module\EmailMarketing\Service\Actions\DeleteTestMailMarketingEntriesService($a, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
