<?php

namespace ContainerWP8FjR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailValidationHelperService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Emails\Service\Validation\EmailValidationHelper' shared autowired service.
     *
     * @return \App\Emails\Service\Validation\EmailValidationHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Emails'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Validation'.\DIRECTORY_SEPARATOR.'EmailValidationHelper.php';

        $a = ($container->privates['App\\Data\\LegacyHandler\\PreparedStatementHandler'] ?? $container->load('getPreparedStatementHandlerService'));

        if (isset($container->privates['App\\Emails\\Service\\Validation\\EmailValidationHelper'])) {
            return $container->privates['App\\Emails\\Service\\Validation\\EmailValidationHelper'];
        }

        return $container->privates['App\\Emails\\Service\\Validation\\EmailValidationHelper'] = new \App\Emails\Service\Validation\EmailValidationHelper($a);
    }
}
