<?php

namespace ContainerWP8FjR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLanguageManagerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Languages\Service\LanguageManager' shared autowired service.
     *
     * @return \App\Languages\Service\LanguageManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Languages'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'LanguageManagerInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Languages'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'LanguageManager.php';

        $a = ($container->privates['App\\FieldDefinitions\\LegacyHandler\\FieldDefinitionsHandler'] ?? $container->load('getFieldDefinitionsHandlerService'));

        if (isset($container->privates['App\\Languages\\Service\\LanguageManager'])) {
            return $container->privates['App\\Languages\\Service\\LanguageManager'];
        }
        $b = ($container->privates['App\\Authentication\\LegacyHandler\\UserHandler'] ?? $container->load('getUserHandlerService'));

        if (isset($container->privates['App\\Languages\\Service\\LanguageManager'])) {
            return $container->privates['App\\Languages\\Service\\LanguageManager'];
        }

        return $container->privates['App\\Languages\\Service\\LanguageManager'] = new \App\Languages\Service\LanguageManager($a, ($container->privates['App\\Languages\\LegacyHandler\\AppListStringsHandler'] ?? $container->load('getAppListStringsHandlerService')), ($container->privates['App\\Languages\\LegacyHandler\\AppStringsHandler'] ?? $container->load('getAppStringsHandlerService')), $b, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
