<?php

namespace ContainerWP8FjR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMediaControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\MediaObjects\Controller\MediaController' shared autowired service.
     *
     * @return \App\MediaObjects\Controller\MediaController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'MediaObjects'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'MediaController.php';

        $container->services['App\\MediaObjects\\Controller\\MediaController'] = $instance = new \App\MediaObjects\Controller\MediaController(($container->privates['App\\MediaObjects\\Repository\\ArchivedDocumentMediaObjectRepository'] ?? self::getArchivedDocumentMediaObjectRepositoryService($container)), ($container->privates['App\\MediaObjects\\Repository\\PrivateDocumentMediaObjectRepository'] ?? self::getPrivateDocumentMediaObjectRepositoryService($container)), ($container->privates['App\\MediaObjects\\Repository\\PrivateImageMediaObjectRepository'] ?? self::getPrivateImageMediaObjectRepositoryService($container)), ($container->privates['App\\Engine\\LegacyHandler\\AclHandler'] ?? $container->load('getAclHandlerService')));

        $instance->setContainer(($container->privates['.service_locator.VUN9NvY'] ?? $container->load('get_ServiceLocator_VUN9NvYService'))->withContext('App\\MediaObjects\\Controller\\MediaController', $container));

        return $instance;
    }
}
