<?php

namespace ContainerWP8FjR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendEmailHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Emails\LegacyHandler\SendEmailHandler' shared autowired service.
     *
     * @return \App\Emails\LegacyHandler\SendEmailHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Emails'.\DIRECTORY_SEPARATOR.'LegacyHandler'.\DIRECTORY_SEPARATOR.'SendEmailHandler.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Emails'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'RecordToEmailMapper'.\DIRECTORY_SEPARATOR.'RecordToEmailService.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'vich'.\DIRECTORY_SEPARATOR.'uploader-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Handler'.\DIRECTORY_SEPARATOR.'AbstractHandler.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'MediaObjects'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'MediaObjectFileHandler.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Emails'.\DIRECTORY_SEPARATOR.'LegacyHandler'.\DIRECTORY_SEPARATOR.'Mailers'.\DIRECTORY_SEPARATOR.'LegacyMailer.php';

        $a = ($container->privates['App\\FieldDefinitions\\LegacyHandler\\FieldDefinitionsHandler'] ?? $container->load('getFieldDefinitionsHandlerService'));

        if (isset($container->privates['App\\Emails\\LegacyHandler\\SendEmailHandler'])) {
            return $container->privates['App\\Emails\\LegacyHandler\\SendEmailHandler'];
        }
        $b = ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState());
        $c = ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack());
        $d = ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container));

        return $container->privates['App\\Emails\\LegacyHandler\\SendEmailHandler'] = new \App\Emails\LegacyHandler\SendEmailHandler(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', $b, $c, $d, new \App\Emails\Service\RecordToEmailMapper\RecordToEmailService(($container->privates['App\\MediaObjects\\Repository\\DefaultMediaObjectManager'] ?? self::getDefaultMediaObjectManagerService($container)), $a, $d, new \App\MediaObjects\Services\MediaObjectFileHandler(($container->privates['vich_uploader.property_mapping_factory'] ?? self::getVichUploader_PropertyMappingFactoryService($container)), ($container->privates['vich_uploader.storage.flysystem'] ?? self::getVichUploader_Storage_FlysystemService($container)))), new \App\Emails\LegacyHandler\Mailers\LegacyMailer(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', $b, $c, $d));
    }
}
