<?php

namespace ContainerWP8FjR0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUuidMediaObjectFileNamerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\MediaObjects\Services\UuidMediaObjectFileNamer' shared autowired service.
     *
     * @return \App\MediaObjects\Services\UuidMediaObjectFileNamer
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->services['App\\MediaObjects\\Services\\UuidMediaObjectFileNamer'] = $container->createProxy('UuidMediaObjectFileNamerGhostB0adbfc', static fn () => \UuidMediaObjectFileNamerGhostB0adbfc::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'vich'.\DIRECTORY_SEPARATOR.'uploader-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Naming'.\DIRECTORY_SEPARATOR.'NamerInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'MediaObjects'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'UuidMediaObjectFileNamer.php';

        return $lazyLoad;
    }
}
